export const JSON_VIEW_LIGHT_THEME: Record<string, string> = {
  "--w-rjv-font-family": "monospace",
  "--w-rjv-color": "#334155",
  "--w-rjv-key-string": "#0284c7",
  "--w-rjv-background-color": "transparent",
  "--w-rjv-line-color": "#e2e8f0",
  "--w-rjv-arrow-color": "#94a3b8",
  "--w-rjv-info-color": "#94a3b8",
  "--w-rjv-update-color": "#d97706",
  "--w-rjv-copied-color": "#0284c7",
  "--w-rjv-copied-success-color": "#059669",
  "--w-rjv-curlybraces-color": "#94a3b8",
  "--w-rjv-colon-color": "#334155",
  "--w-rjv-brackets-color": "#94a3b8",
  "--w-rjv-quotes-color": "var(--w-rjv-key-string)",
  "--w-rjv-quotes-string-color": "var(--w-rjv-type-string-color)",
  "--w-rjv-type-string-color": "#059669",
  "--w-rjv-type-int-color": "#ea580c",
  "--w-rjv-type-float-color": "#ea580c",
  "--w-rjv-type-bigint-color": "#ea580c",
  "--w-rjv-type-boolean-color": "#d97706",
  "--w-rjv-type-date-color": "#94a3b8",
  "--w-rjv-type-url-color": "#0284c7",
  "--w-rjv-type-null-color": "#94a3b8",
  "--w-rjv-type-nan-color": "#94a3b8",
  "--w-rjv-type-undefined-color": "#94a3b8",
};

export const JSON_VIEW_DARK_THEME: Record<string, string> = {
  "--w-rjv-font-family": "monospace",
  "--w-rjv-color": "#e5e5e5",
  "--w-rjv-key-string": "#38bdf8",
  "--w-rjv-background-color": "transparent",
  "--w-rjv-line-color": "#404040",
  "--w-rjv-arrow-color": "#a3a3a3",
  "--w-rjv-info-color": "#737373",
  "--w-rjv-update-color": "#fbbf24",
  "--w-rjv-copied-color": "#38bdf8",
  "--w-rjv-copied-success-color": "#34d399",
  "--w-rjv-curlybraces-color": "#737373",
  "--w-rjv-colon-color": "#e5e5e5",
  "--w-rjv-brackets-color": "#737373",
  "--w-rjv-quotes-color": "var(--w-rjv-key-string)",
  "--w-rjv-quotes-string-color": "var(--w-rjv-type-string-color)",
  "--w-rjv-type-string-color": "#34d399",
  "--w-rjv-type-int-color": "#fb923c",
  "--w-rjv-type-float-color": "#fb923c",
  "--w-rjv-type-bigint-color": "#fb923c",
  "--w-rjv-type-boolean-color": "#fbbf24",
  "--w-rjv-type-date-color": "#a3a3a3",
  "--w-rjv-type-url-color": "#38bdf8",
  "--w-rjv-type-null-color": "#a3a3a3",
  "--w-rjv-type-nan-color": "#a3a3a3",
  "--w-rjv-type-undefined-color": "#a3a3a3",
};
