import type { FieldOption } from "../../types/field";

// Volcado literal de los endpoints de catalogo, sin retocar: los ids y las etiquetas son los que
// devuelve la API de verdad, incluidas sus rarezas (CUNDINAMARCA aparece dos veces, "V ALLE DEL
// CAUCA" viene con el espacio partido). Corregirlas aca haria que el simulador mintiera justo
// donde tiene que ser fiel. Archivo generado: regenerar desde el volcado, no editar a mano.
//
// ACTIVIDADES salio de un volcado aparte, con otra forma: cada fila trae idDeclaracion, codigoCIIU,
// descripcion y tarifaXMil. Se toma idDeclaracion como id porque la plantilla ya lleva un campo
// "Codigo" separado para el CIIU, asi que no pueden ser el mismo valor. La tarifa se descarto al
// convertir: FieldOption solo tiene id y label, y todavia no esta decidido como llega a los campos
// codigo_actividad y tarifa_x_mil, que hoy quedan vacios y deshabilitados.

export const TIPOS_DOCUMENTO: FieldOption[] = [
  { id: "1", label: "CEDULA" },
  { id: "2", label: "NIT" },
  { id: "3", label: "TARJETA IDENTIDAD" },
  { id: "4", label: "CEDULA EXTRANJERIA" },
];

// Ojo: idTipoPersona no es natural/juridica, es la lista de personas NO convencionales.
export const TIPOS_PERSONA: FieldOption[] = [
  { id: "1", label: "ES CONSORCIO O UNION TEMPORAL" },
  { id: "2", label: "REALIZA ACTIVIDADES A TRAVÉS DE PATRIMONIO AUTÓNOMO" },
];

export const PERIODOS_ANUALES: FieldOption[] = [
  { id: "1", label: "Enero - Febrero" },
  { id: "2", label: "Marzo - Abril" },
  { id: "3", label: "Mayo - Junio" },
  { id: "4", label: "Julio - Agosto" },
  { id: "5", label: "Septiembre - Octubre" },
  { id: "6", label: "Noviembre - Diciembre" },
  { id: "7", label: "Anual" },
];

export const TIPOS_DECLARACION: FieldOption[] = [
  { id: "1", label: "DECLARACIÓN INICIAL" },
  { id: "2", label: "CORECCIÓN" },
  { id: "3", label: "CLAUSURA" },
];

export const TIPOS_SANCION: FieldOption[] = [
  { id: "1", label: "EXTEMPORANEIDAD" },
  { id: "2", label: "CORECCIÓN" },
  { id: "3", label: "INEXACTITUD" },
  { id: "4", label: "OTRA" },
];

export const JUEGOS_PERMITIDOS: FieldOption[] = [
  { id: "1", label: "TEJO O TUMERQUÉ" },
  { id: "2", label: "BILLARES" },
  { id: "3", label: "VIDEO JUEGOS" },
  { id: "4", label: "GALLERAS" },
];

export const DEPARTAMENTOS: FieldOption[] = [
  { id: "1", label: "ANTIOQUIA" },
  { id: "2", label: "ATLANTICO" },
  { id: "3", label: "CUNDINAMARCA" },
  { id: "4", label: "BOLIVAR" },
  { id: "5", label: "BOYACA" },
  { id: "6", label: "CALDAS" },
  { id: "7", label: "CAQUETA" },
  { id: "8", label: "CAUCA" },
  { id: "9", label: "CESAR" },
  { id: "10", label: "CORDOBA" },
  { id: "11", label: "CUNDINAMARCA" },
  { id: "12", label: "CHOCO" },
  { id: "13", label: "HUILA" },
  { id: "14", label: "LA GUAJIRA" },
  { id: "15", label: "MAGDALENA" },
  { id: "16", label: "META" },
  { id: "17", label: "NARIÑO" },
  { id: "18", label: "NORTE DE SANTANDER" },
  { id: "19", label: "QUINDIO" },
  { id: "20", label: "RISARALDA" },
  { id: "21", label: "SANTANDER" },
  { id: "22", label: "SUCRE" },
  { id: "23", label: "TOLIMA" },
  { id: "24", label: "V ALLE DEL CAUCA" },
  { id: "25", label: "ARAUCA" },
  { id: "26", label: "CASANARE" },
  { id: "27", label: "PUTUMAYO" },
  { id: "28", label: "SAN ANDRES" },
  { id: "29", label: "AMAZONAS" },
  { id: "30", label: "GUIANIA" },
  { id: "31", label: "GUAVIARE" },
  { id: "32", label: "VAUPES" },
  { id: "33", label: "VICHADA" },
];

export const MUNICIPIOS_POR_DEPARTAMENTO: Record<string, FieldOption[]> = {
  "1": [
    { id: "1", label: "MEDELLIN" },
    { id: "2", label: "ABEJORRAL" },
    { id: "3", label: "ABRIAQUÍ" },
    { id: "4", label: "ALEJANDRÍA" },
    { id: "5", label: "AMAGÁ" },
    { id: "6", label: "AMALFI" },
    { id: "7", label: "ANDES" },
    { id: "8", label: "ANGELÓPOLIS" },
    { id: "9", label: "ANGOSTURA" },
    { id: "10", label: "ANORÍ" },
    { id: "11", label: "ANTIOQUIA" },
    { id: "12", label: "ANZA" },
    { id: "13", label: "APARTADÓ" },
    { id: "14", label: "ARBOLETES" },
    { id: "15", label: "ARGELIA" },
    { id: "16", label: "ARMENIA" },
    { id: "17", label: "BARBOSA" },
    { id: "18", label: "BELMIRA" },
    { id: "19", label: "BELLO" },
    { id: "20", label: "BETANIA" },
    { id: "21", label: "BETULIA" },
    { id: "22", label: "BOLÍVAR" },
    { id: "23", label: "BRICEÑO" },
    { id: "24", label: "BURITICÁ" },
    { id: "25", label: "CÁCERES" },
    { id: "26", label: "CAICEDO" },
    { id: "27", label: "CALDAS" },
    { id: "28", label: "CAMPAMENTO" },
    { id: "29", label: "CAÑASGORDAS" },
    { id: "30", label: "CARACOLÍ" },
    { id: "31", label: "CARAMANTA" },
    { id: "32", label: "CAREPA" },
    { id: "33", label: "CARMEN DE VIBORAL" },
    { id: "34", label: "CAROLINA" },
    { id: "35", label: "CAUCASIA" },
    { id: "36", label: "CHIGORODÓ" },
    { id: "37", label: "CISNEROS" },
    { id: "38", label: "COCORNÁ" },
    { id: "39", label: "CONCEPCIÓN" },
    { id: "40", label: "CONCORDIA" },
    { id: "41", label: "COPACABANA" },
    { id: "42", label: "DABEIBA" },
    { id: "43", label: "DON MATÍAS" },
    { id: "44", label: "EBÉJICO" },
    { id: "45", label: "EL BAGRE" },
    { id: "46", label: "ENTRERRIOS" },
    { id: "47", label: "ENVIGADO" },
    { id: "48", label: "FREDONIA" },
    { id: "49", label: "FRONTINO" },
    { id: "50", label: "GIRALDO" },
    { id: "51", label: "GIRARDOTA" },
    { id: "52", label: "GÓMEZ PLATA" },
    { id: "53", label: "GRANADA" },
    { id: "54", label: "GUADALUPE" },
    { id: "55", label: "GUARNE" },
    { id: "56", label: "GUATAPE" },
    { id: "57", label: "HELICONIA" },
    { id: "58", label: "HISPANIA" },
    { id: "59", label: "ITAGUI" },
    { id: "60", label: "ITUANGO" },
    { id: "61", label: "JARDÍN" },
    { id: "62", label: "JERICÓ" },
    { id: "63", label: "LA CEJA" },
    { id: "64", label: "LA ESTRELLA" },
    { id: "65", label: "LA PINTADA" },
    { id: "66", label: "LA UNIÓN" },
    { id: "67", label: "LIBORINA" },
    { id: "68", label: "MACEO" },
    { id: "69", label: "MARINILLA" },
    { id: "70", label: "MONTEBELLO" },
    { id: "71", label: "MURINDÓ" },
    { id: "72", label: "MUTATÁ" },
    { id: "73", label: "NARIÑO" },
    { id: "74", label: "NECOCLÍ" },
    { id: "75", label: "NECHÍ" },
    { id: "76", label: "OLAYA" },
    { id: "77", label: "PEÑOL" },
    { id: "78", label: "PEQUE" },
    { id: "79", label: "PUEBLORRICO" },
    { id: "80", label: "PUERTO BERRIO" },
    { id: "81", label: "PUERTO NARE" },
    { id: "82", label: "PUERTO TRIUNFO" },
    { id: "83", label: "REMEDIOS" },
    { id: "84", label: "RETIRO" },
    { id: "85", label: "RIONEGRO" },
    { id: "86", label: "SABANALARGA" },
    { id: "87", label: "SABANETA" },
    { id: "88", label: "SALGAR" },
    { id: "89", label: "SAN ANDRÉS" },
    { id: "90", label: "SAN CARLOS" },
    { id: "91", label: "SAN FRANCISCO" },
    { id: "92", label: "SAN JERÓNIMO" },
    { id: "93", label: "SAN JOSÉ DE LA MONTAÑA" },
    { id: "94", label: "SAN JUAN DE URABA" },
    { id: "95", label: "SAN LUIS" },
    { id: "96", label: "SAN PEDRO" },
    { id: "97", label: "SAN PEDRO DE URABA" },
    { id: "98", label: "SAN RAFAEL" },
    { id: "99", label: "SAN ROQUE" },
    { id: "100", label: "SAN VICENTE" },
    { id: "101", label: "SANTA BÁRBARA" },
    { id: "102", label: "SANTA ROSA DE OSOS" },
    { id: "103", label: "SANTO DOMINGO" },
    { id: "104", label: "EL SANTUARIO" },
    { id: "105", label: "SEGOVIA" },
    { id: "106", label: "SONSÓN" },
    { id: "107", label: "SOPETRÁN" },
    { id: "108", label: "TÁMESIS" },
    { id: "109", label: "TARAZÁ" },
    { id: "110", label: "TARSO" },
    { id: "111", label: "TITIRIBÍ" },
    { id: "112", label: "TOLEDO" },
    { id: "113", label: "TURBO" },
    { id: "114", label: "URAMITA" },
    { id: "115", label: "URRAO" },
    { id: "116", label: "VALDIVIA" },
    { id: "117", label: "VALPARAÍSO" },
    { id: "118", label: "VEGACHÍ" },
    { id: "119", label: "VENECIA" },
    { id: "120", label: "VIGÍA DEL FUERTE" },
    { id: "121", label: "YALÍ" },
    { id: "122", label: "YARUMAL" },
    { id: "123", label: "YOLOMBÓ" },
    { id: "124", label: "YONDÓ" },
    { id: "125", label: "ZARAGOZA" },
  ],
  "2": [
    { id: "126", label: "BARRANQUILLA" },
    { id: "127", label: "BARANOA" },
    { id: "128", label: "CAMPO DE LA CRUZ" },
    { id: "129", label: "CANDELARIA" },
    { id: "130", label: "GALAPA" },
    { id: "131", label: "JUAN DE ACOSTA" },
    { id: "132", label: "LURUACO" },
    { id: "133", label: "MALAMBO" },
    { id: "134", label: "MANATÍ" },
    { id: "135", label: "PALMAR DE VARELA" },
    { id: "136", label: "PIOJÓ" },
    { id: "137", label: "POLO NUEVO" },
    { id: "138", label: "PONEDERA" },
    { id: "139", label: "PUERTO COLOMBIA" },
    { id: "140", label: "REPELÓN" },
    { id: "141", label: "SABANAGRANDE" },
    { id: "142", label: "SABANALARGA" },
    { id: "143", label: "SANTA LUCÍA" },
    { id: "144", label: "SANTO TOMÁS" },
    { id: "145", label: "SOLEDAD" },
    { id: "146", label: "SUAN" },
    { id: "147", label: "TUBARÁ" },
    { id: "148", label: "USIACURÍ" },
  ],
  "3": [{ id: "149", label: "BOGOTÁ" }],
  "4": [
    { id: "150", label: "CARTAGENA" },
    { id: "151", label: "ACHÍ" },
    { id: "152", label: "ALTOS DEL ROSARIO" },
    { id: "153", label: "ARENAL" },
    { id: "154", label: "ARJONA" },
    { id: "155", label: "ARROYOHONDO" },
    { id: "156", label: "BARRANCO DE LOBA" },
    { id: "157", label: "CALAMAR" },
    { id: "158", label: "CANTAGALLO" },
    { id: "159", label: "CICUCO" },
    { id: "160", label: "CÓRDOBA" },
    { id: "161", label: "CLEMENCIA" },
    { id: "162", label: "CARMEN DE BOLÍVAR" },
    { id: "163", label: "EL GUAMO" },
    { id: "164", label: "EL PEÑON" },
    { id: "165", label: "HATILLO DE LOBA" },
    { id: "166", label: "MAGANGUE" },
    { id: "167", label: "MAHATES" },
    { id: "168", label: "MARGARITA" },
    { id: "169", label: "MARÍA LA BAJA" },
    { id: "170", label: "MONTECRISTO" },
    { id: "171", label: "MOMPOS" },
    { id: "172", label: "MORALES" },
    { id: "173", label: "PINILLOS" },
    { id: "174", label: "REGIDOR" },
    { id: "175", label: "RÍO VIEJO" },
    { id: "176", label: "SAN CRISTÓBAL" },
    { id: "177", label: "SAN ESTANISLAO" },
    { id: "178", label: "SAN FERNANDO" },
    { id: "179", label: "SAN JACINTO" },
    { id: "180", label: "SAN JACINTO DEL CAUCA" },
    { id: "181", label: "SAN JUAN NEPOMUCENO" },
    { id: "182", label: "SAN MARTÍN LOBA" },
    { id: "183", label: "SAN PABLO" },
    { id: "184", label: "STA CATALINA" },
    { id: "185", label: "SANTA ROSA" },
    { id: "186", label: "STA ROSA SUR" },
    { id: "187", label: "SIMITI" },
    { id: "188", label: "SOPLAVIENTO" },
    { id: "189", label: "TALAIGUA NUEVO" },
    { id: "190", label: "TIQUISIO (PUERTO RICO)" },
    { id: "191", label: "TURBACO" },
    { id: "192", label: "TURBANÁ" },
    { id: "193", label: "VILLANUEVA" },
    { id: "194", label: "ZAMBRANO" },
  ],
  "5": [
    { id: "195", label: "TUNJA" },
    { id: "196", label: "ALMEIDA" },
    { id: "197", label: "AQUITANIA" },
    { id: "198", label: "ARCABUCO" },
    { id: "199", label: "BELÉN" },
    { id: "200", label: "BERBEO" },
    { id: "201", label: "BETÉITIVA" },
    { id: "202", label: "BOAVITA" },
    { id: "203", label: "BOYACÁ" },
    { id: "204", label: "BRICEÑO" },
    { id: "205", label: "BUENAVISTA" },
    { id: "206", label: "BUSBANZA" },
    { id: "207", label: "CALDAS" },
    { id: "208", label: "CAMPOHERMOSO" },
    { id: "209", label: "CERINZA" },
    { id: "210", label: "CHINAVITA" },
    { id: "211", label: "CHIQUINQUIRÁ" },
    { id: "212", label: "CHISCAS" },
    { id: "213", label: "CHITA" },
    { id: "214", label: "CHITARAQUE" },
    { id: "215", label: "CHIVATÁ" },
    { id: "216", label: "CIÉNEGA" },
    { id: "217", label: "CÓMBITA" },
    { id: "218", label: "COPER" },
    { id: "219", label: "CORRALES" },
    { id: "220", label: "COVARACHÍA" },
    { id: "221", label: "CUBARÁ" },
    { id: "222", label: "CUCAITA" },
    { id: "223", label: "CUÍTIVA" },
    { id: "224", label: "CHÍQUIZA" },
    { id: "225", label: "CHIVOR" },
    { id: "226", label: "DUITAMA" },
    { id: "227", label: "EL COCUY" },
    { id: "228", label: "EL ESPINO" },
    { id: "229", label: "FIRAVITOBA" },
    { id: "230", label: "FLORESTA" },
    { id: "231", label: "GACHANTIVÁ" },
    { id: "232", label: "GAMEZA" },
    { id: "233", label: "GARAGOA" },
    { id: "234", label: "GUACAMAYAS" },
    { id: "235", label: "GUATEQUE" },
    { id: "236", label: "GUAYATÁ" },
    { id: "237", label: "GUICAN" },
    { id: "238", label: "IZA" },
    { id: "239", label: "JENESANO" },
    { id: "240", label: "JERICÓ" },
    { id: "241", label: "LABRANZAGRANDE" },
    { id: "242", label: "LA CAPILLA" },
    { id: "243", label: "LA VICTORIA" },
    { id: "244", label: "LA UVITA" },
    { id: "245", label: "VILLA DE LEYVA" },
    { id: "246", label: "MACANAL" },
    { id: "247", label: "MARIPÍ" },
    { id: "248", label: "MIRAFLORES" },
    { id: "249", label: "MONGUA" },
    { id: "250", label: "MONGUÍ" },
    { id: "251", label: "MONIQUIRÁ" },
    { id: "252", label: "MOTAVITA" },
    { id: "253", label: "MUZO" },
    { id: "254", label: "NOBSA" },
    { id: "255", label: "NUEVO COLÓN" },
    { id: "256", label: "OICATÁ" },
    { id: "257", label: "OTANCHE" },
    { id: "258", label: "PACHAVITA" },
    { id: "259", label: "PÁEZ" },
    { id: "260", label: "PAIPA" },
    { id: "261", label: "PAJARITO" },
    { id: "262", label: "PANQUEBA" },
    { id: "263", label: "PAUNA" },
    { id: "264", label: "PAYA" },
    { id: "265", label: "PAZ DE RÍO" },
    { id: "266", label: "PESCA" },
    { id: "267", label: "PISBA" },
    { id: "268", label: "PUERTO BOYACÁ" },
    { id: "269", label: "QUÍPAMA" },
    { id: "270", label: "RAMIRIQUÍ" },
    { id: "271", label: "RÁQUIRA" },
    { id: "272", label: "RONDÓN" },
    { id: "273", label: "SABOYÁ" },
    { id: "274", label: "SÁCHICA" },
    { id: "275", label: "SAMACÁ" },
    { id: "276", label: "SAN EDUARDO" },
    { id: "277", label: "SAN JOSÉ DE PARE" },
    { id: "278", label: "SAN LUIS DE GACENO" },
    { id: "279", label: "SAN MATEO" },
    { id: "280", label: "SAN MIGUEL DE SEMA" },
    { id: "281", label: "SAN PABLO DE BORBUR" },
    { id: "282", label: "SANTANA" },
    { id: "283", label: "SANTA MARÍA" },
    { id: "284", label: "SANTA ROSA DE VITERBO" },
    { id: "285", label: "SANTA SOFÍA" },
    { id: "286", label: "SATIVANORTE" },
    { id: "287", label: "SATIVASUR" },
    { id: "288", label: "SIACHOQUE" },
    { id: "289", label: "SOATA" },
    { id: "290", label: "SOCOTA" },
    { id: "291", label: "SOCHA" },
    { id: "292", label: "SOGAMOSO" },
    { id: "293", label: "SOMONDOCO" },
    { id: "294", label: "SORA" },
    { id: "295", label: "SOTAQUIRÁ" },
    { id: "296", label: "SORACÁ" },
    { id: "297", label: "SUSACÓN" },
    { id: "298", label: "SUTAMARCHÁN" },
    { id: "299", label: "SUTATENZA" },
    { id: "300", label: "TASCO" },
    { id: "301", label: "TENZA" },
    { id: "302", label: "TIBANÁ" },
    { id: "303", label: "TIBASOSA" },
    { id: "304", label: "TINJACÁ" },
    { id: "305", label: "TIPACOQUE" },
    { id: "306", label: "TOCA" },
    { id: "307", label: "TOGUI" },
    { id: "308", label: "TÓPAGA" },
    { id: "309", label: "TOTA" },
    { id: "310", label: "TUNUNGUÁ" },
    { id: "311", label: "TURMEQUÉ" },
    { id: "312", label: "TUTA" },
    { id: "313", label: "TUTAZÁ" },
    { id: "314", label: "UMBITA" },
    { id: "315", label: "VENTAQUEMADA" },
    { id: "316", label: "VIRACACHÁ" },
    { id: "317", label: "ZETAQUIRA" },
  ],
  "6": [
    { id: "318", label: "MANIZALES" },
    { id: "319", label: "AGUADAS" },
    { id: "320", label: "ANSERMA" },
    { id: "321", label: "ARANZAZU" },
    { id: "322", label: "BELALCÁZAR" },
    { id: "323", label: "CHINCHINÁ" },
    { id: "324", label: "FILADELFIA" },
    { id: "325", label: "LA DORADA" },
    { id: "326", label: "LA MERCED" },
    { id: "327", label: "MANZANARES" },
    { id: "328", label: "MARMATO" },
    { id: "329", label: "MARQUETALIA" },
    { id: "330", label: "MARULANDA" },
    { id: "331", label: "NEIRA" },
    { id: "332", label: "NORCASIA" },
    { id: "333", label: "PÁCORA" },
    { id: "334", label: "PALESTINA" },
    { id: "335", label: "PENSILVANIA" },
    { id: "336", label: "RIOSUCIO" },
    { id: "337", label: "RISARALDA" },
    { id: "338", label: "SALAMINA" },
    { id: "339", label: "SAMANÁ" },
    { id: "340", label: "SAN JOSÉ" },
    { id: "341", label: "SUPÍA" },
    { id: "342", label: "VICTORIA" },
    { id: "343", label: "VILLAMARÍA" },
    { id: "344", label: "VITERBO" },
  ],
  "7": [
    { id: "345", label: "FLORENCIA" },
    { id: "346", label: "ALBANIA" },
    { id: "347", label: "BELÉN DE LOS ANDAQUIES" },
    { id: "348", label: "CARTAGENA DEL CHAIRÁ" },
    { id: "349", label: "CURILLO" },
    { id: "350", label: "EL DONCELLO" },
    { id: "351", label: "EL PAUJIL" },
    { id: "352", label: "LA MONTAÑITA" },
    { id: "353", label: "MILÁN" },
    { id: "354", label: "MORELIA" },
    { id: "355", label: "PUERTO RICO" },
    { id: "356", label: "SAN JOSÉ DEL FRAGUA" },
    { id: "357", label: "SAN VICENTE DEL CAGUÁN" },
    { id: "358", label: "SOLANO" },
    { id: "359", label: "SOLITA" },
    { id: "360", label: "VALPARAÍSO" },
  ],
  "8": [
    { id: "361", label: "POPAYÁN" },
    { id: "362", label: "ALMAGUER" },
    { id: "363", label: "ARGELIA" },
    { id: "364", label: "BALBOA" },
    { id: "365", label: "BOLÍVAR" },
    { id: "366", label: "BUENOS AIRES" },
    { id: "367", label: "CAJIBÍO" },
    { id: "368", label: "CALDONO" },
    { id: "369", label: "CALOTO" },
    { id: "370", label: "CORINTO" },
    { id: "371", label: "EL TAMBO" },
    { id: "372", label: "FLORENCIA" },
    { id: "373", label: "GUAPI" },
    { id: "374", label: "INZÁ" },
    { id: "375", label: "JAMBALÓ" },
    { id: "376", label: "LA SIERRA" },
    { id: "377", label: "LA VEGA" },
    { id: "378", label: "LÓPEZ DE MICAY" },
    { id: "379", label: "MERCADERES" },
    { id: "380", label: "MIRANDA" },
    { id: "381", label: "MORALES" },
    { id: "382", label: "PADILLA" },
    { id: "383", label: "PÁEZ" },
    { id: "384", label: "PATÍA" },
    { id: "385", label: "PIAMONTE" },
    { id: "386", label: "PIÉNDAMO" },
    { id: "387", label: "PUERTO TEJADA" },
    { id: "388", label: "PURACÉ" },
    { id: "389", label: "ROSAS" },
    { id: "390", label: "SAN SEBASTIÁN" },
    { id: "391", label: "SANTANDER DE QUILICHAO" },
    { id: "392", label: "SANTA ROSA" },
    { id: "393", label: "SILVIA" },
    { id: "394", label: "SOTARA" },
    { id: "395", label: "SUÁREZ" },
    { id: "396", label: "SUCRE" },
    { id: "397", label: "TIMBÍO" },
    { id: "398", label: "TIMBIQUÍ" },
    { id: "399", label: "TORIBIO" },
    { id: "400", label: "TOTORÓ" },
    { id: "401", label: "VILLA RICA" },
  ],
  "9": [
    { id: "402", label: "VALLEDUPAR" },
    { id: "403", label: "AGUACHICA" },
    { id: "404", label: "AGUSTÍN CODAZZI" },
    { id: "405", label: "ASTREA" },
    { id: "406", label: "BECERRIL" },
    { id: "407", label: "BOSCONIA" },
    { id: "408", label: "CHIMICHAGUA" },
    { id: "409", label: "CHIRIGUANÁ" },
    { id: "410", label: "CURUMANÍ" },
    { id: "411", label: "EL COPEY" },
    { id: "412", label: "EL PASO" },
    { id: "413", label: "GAMARRA" },
    { id: "414", label: "GONZÁLEZ" },
    { id: "415", label: "LA GLORIA" },
    { id: "416", label: "LA JAGUA DE IBIRICO" },
    { id: "417", label: "MANAURE BALCÓN CESAR" },
    { id: "418", label: "PAILITAS" },
    { id: "419", label: "PELAYA" },
    { id: "420", label: "PUEBLO BELLO" },
    { id: "421", label: "RÍO DE ORO" },
    { id: "422", label: "LA PAZ" },
    { id: "423", label: "SAN ALBERTO" },
    { id: "424", label: "SAN DIEGO" },
    { id: "425", label: "SAN MARTÍN" },
    { id: "426", label: "TAMALAMEQUE" },
  ],
  "10": [
    { id: "427", label: "MONTERÍA" },
    { id: "428", label: "AYAPEL" },
    { id: "429", label: "BUENAVISTA" },
    { id: "430", label: "CANALETE" },
    { id: "431", label: "CERETÉ" },
    { id: "432", label: "CHIMÁ" },
    { id: "433", label: "CHINÚ" },
    { id: "434", label: "CIÉNAGA DE ORO" },
    { id: "435", label: "COTORRA" },
    { id: "436", label: "LA APARTADA" },
    { id: "437", label: "LORICA" },
    { id: "438", label: "LOS CÓRDOBAS" },
    { id: "439", label: "MOMIL" },
    { id: "440", label: "MONTELÍBANO" },
    { id: "441", label: "MOÑITOS" },
    { id: "442", label: "PLANETA RICA" },
    { id: "443", label: "PUEBLO NUEVO" },
    { id: "444", label: "PUERTO ESCONDIDO" },
    { id: "445", label: "PUERTO LIBERTADOR" },
    { id: "446", label: "PURÍSIMA" },
    { id: "447", label: "SAHAGÚN" },
    { id: "448", label: "SAN ANDRÉS SOTAVENTO" },
    { id: "449", label: "SAN ANTERO" },
    { id: "450", label: "SAN BERNARDO DEL VIENTO" },
    { id: "451", label: "SAN CARLOS" },
    { id: "452", label: "SAN PELAYO" },
    { id: "453", label: "TIERRALTA" },
    { id: "454", label: "VALENCIA" },
  ],
  "11": [
    { id: "455", label: "AGUA DE DIOS" },
    { id: "456", label: "ALBÁN" },
    { id: "457", label: "ANAPOIMA" },
    { id: "458", label: "ANOLAIMA" },
    { id: "459", label: "ARBELÁEZ" },
    { id: "460", label: "BELTRÁN" },
    { id: "461", label: "BITUIMA" },
    { id: "462", label: "BOJACÁ" },
    { id: "463", label: "CABRERA" },
    { id: "464", label: "CACHIPAY" },
    { id: "465", label: "CAJICÁ" },
    { id: "466", label: "CAPARRAPÍ" },
    { id: "467", label: "CAQUEZA" },
    { id: "468", label: "CARMEN DE CARUPA" },
    { id: "469", label: "CHAGUANÍ" },
    { id: "470", label: "CHÍA" },
    { id: "471", label: "CHIPAQUE" },
    { id: "472", label: "CHOACHÍ" },
    { id: "473", label: "CHOCONTÁ" },
    { id: "474", label: "COGUA" },
    { id: "475", label: "COTA" },
    { id: "476", label: "CUCUNUBÁ" },
    { id: "477", label: "EL COLEGIO" },
    { id: "478", label: "EL PEÑON" },
    { id: "479", label: "EL ROSAL" },
    { id: "480", label: "FACATATIVÁ" },
    { id: "481", label: "FOMEQUE" },
    { id: "482", label: "FOSCA" },
    { id: "483", label: "FUNZA" },
    { id: "484", label: "FÚQUENE" },
    { id: "485", label: "FUSAGASUGÁ" },
    { id: "486", label: "GACHALA" },
    { id: "487", label: "GACHANCIPÁ" },
    { id: "488", label: "GACHETÁ" },
    { id: "489", label: "GAMA" },
    { id: "490", label: "GIRARDOT" },
    { id: "491", label: "GRANADA" },
    { id: "492", label: "GUACHETÁ" },
    { id: "493", label: "GUADUAS" },
    { id: "494", label: "GUASCA" },
    { id: "495", label: "GUATAQUÍ" },
    { id: "496", label: "GUATAVITA" },
    { id: "497", label: "GUAYABAL DE SIQUIMA" },
    { id: "498", label: "GUAYABETAL" },
    { id: "499", label: "GUTIÉRREZA" },
    { id: "500", label: "JERUSALÉN" },
    { id: "501", label: "JUNÍN" },
    { id: "502", label: "LA CALERA" },
    { id: "503", label: "LA MESA" },
    { id: "504", label: "LA PALMA" },
    { id: "505", label: "LA PEÑA" },
    { id: "506", label: "LA VEGA" },
    { id: "507", label: "LENGUAZAQUE" },
    { id: "508", label: "MACHETA" },
    { id: "509", label: "MADRID" },
    { id: "510", label: "MANTA" },
    { id: "511", label: "MEDINA" },
    { id: "512", label: "MOSQUERA" },
    { id: "513", label: "NARIÑO" },
    { id: "514", label: "NEMOCÓN" },
    { id: "515", label: "NILO" },
    { id: "516", label: "NIMAIMA" },
    { id: "517", label: "NOCAIMA" },
    { id: "518", label: "VENECIA OSPINA PÉREZ" },
    { id: "519", label: "PACHO" },
    { id: "520", label: "PAIME" },
    { id: "521", label: "PANDI" },
    { id: "522", label: "PARATEBUENO" },
    { id: "523", label: "PASCA" },
    { id: "524", label: "PUERTO SALGAR" },
    { id: "525", label: "PULÍ" },
    { id: "526", label: "QUEBRADANEGRA" },
    { id: "527", label: "QUETAME" },
    { id: "528", label: "QUIPILE" },
    { id: "529", label: "APULO" },
    { id: "530", label: "RICAURTE" },
    { id: "531", label: "SAN ANTONIO DE TEQUENDAMA" },
    { id: "532", label: "SAN BERNARDO" },
    { id: "533", label: "SAN CAYETANO" },
    { id: "534", label: "SAN FRANCISCO" },
    { id: "535", label: "SAN JUAN DE RIOSECO" },
    { id: "536", label: "SASAIMA" },
    { id: "537", label: "SESQUILÉ" },
    { id: "538", label: "SIBATÉ" },
    { id: "539", label: "SILVANIA" },
    { id: "540", label: "SIMIJACA" },
    { id: "541", label: "SOACHA" },
    { id: "542", label: "SOPÓ" },
    { id: "543", label: "SUBACHOQUE" },
    { id: "544", label: "SUESCA" },
    { id: "545", label: "SUPATÁ" },
    { id: "546", label: "SUSA" },
    { id: "547", label: "SUTATAUSA" },
    { id: "548", label: "TABIO" },
    { id: "549", label: "TAUSA" },
    { id: "550", label: "TENA" },
    { id: "551", label: "TENJO" },
    { id: "552", label: "TIBACUY" },
    { id: "553", label: "TIBIRITÁ" },
    { id: "554", label: "TOCAIMA" },
    { id: "555", label: "TOCANCIPÁ" },
    { id: "556", label: "TOPAIPI" },
    { id: "557", label: "UBALÁ" },
    { id: "558", label: "UBAQUE" },
    { id: "559", label: "VILLA DE SAN DIEGO DE UBA" },
    { id: "560", label: "UNE" },
    { id: "561", label: "ÚTICA" },
    { id: "562", label: "VERGARA" },
    { id: "563", label: "VIANÍ" },
    { id: "564", label: "VILLAGÓMEZ" },
    { id: "565", label: "VILLA PINZÓN" },
    { id: "566", label: "VILLETA" },
    { id: "567", label: "VIOTÁ" },
    { id: "568", label: "YACOPÍ" },
    { id: "569", label: "ZIPACÓN" },
    { id: "570", label: "ZIPAQUIRÁ" },
  ],
  "12": [
    { id: "571", label: "QUIBDÓ" },
    { id: "572", label: "ACANDÍ" },
    { id: "573", label: "ALTO BAUDÓ" },
    { id: "574", label: "ATRATO YUTO" },
    { id: "575", label: "BAGADÓ" },
    { id: "576", label: "BAHÍA SOLANO" },
    { id: "577", label: "BAJO BAUDÓ PIZARRO" },
    { id: "578", label: "BELÉN DE BAJIRÁ" },
    { id: "579", label: "BELLAVISTA" },
    { id: "580", label: "CANTÓN DEL SAN PABLO" },
    { id: "581", label: "CARMEN DEL DARIÉN" },
    { id: "582", label: "CÉRTEGUI" },
    { id: "583", label: "CONDOTO" },
    { id: "584", label: "EL CARMEN DE ATRATO" },
    { id: "585", label: "EL LITORAL DEL SAN JUAN" },
    { id: "586", label: "ISTMINA" },
    { id: "587", label: "JURADÓ" },
    { id: "588", label: "LLORÓ" },
    { id: "589", label: "MEDIO ATRATO" },
    { id: "590", label: "MEDIO BAUDÓ" },
    { id: "591", label: "MEDIO SAN JUAN" },
    { id: "592", label: "NOVITA" },
    { id: "593", label: "NUQUÍ" },
    { id: "594", label: "RÍO IRO" },
    { id: "595", label: "RÍO QUITO" },
    { id: "596", label: "RIOSUCIO" },
    { id: "597", label: "SAN JOSÉ DEL PALMAR" },
    { id: "598", label: "SIPÍ" },
    { id: "599", label: "TADÓ" },
    { id: "600", label: "UNGUÍA" },
    { id: "601", label: "UNIÓN PANAMERICANA" },
  ],
  "13": [
    { id: "602", label: "NEIVA" },
    { id: "603", label: "ACEVEDO" },
    { id: "604", label: "AGRADO" },
    { id: "605", label: "AIPE" },
    { id: "606", label: "ALGECIRAS" },
    { id: "607", label: "ALTAMIRA" },
    { id: "608", label: "BARAYA" },
    { id: "609", label: "CAMPOALEGRE" },
    { id: "610", label: "COLOMBIA" },
    { id: "611", label: "ELÍAS" },
    { id: "612", label: "GARZÓN" },
    { id: "613", label: "GIGANTE" },
    { id: "614", label: "GUADALUPE" },
    { id: "615", label: "HOBO" },
    { id: "616", label: "ÍQUIRA" },
    { id: "617", label: "ISNOS" },
    { id: "618", label: "LA ARGENTINA" },
    { id: "619", label: "LA PLATA" },
    { id: "620", label: "NÁTAGA" },
    { id: "621", label: "OPORAPA" },
    { id: "622", label: "PAICOL" },
    { id: "623", label: "PALERMO" },
    { id: "624", label: "PALESTINA" },
    { id: "625", label: "PITAL" },
    { id: "626", label: "PITALITO" },
    { id: "627", label: "RIVERA" },
    { id: "628", label: "SALADOBLANCO" },
    { id: "629", label: "SAN AGUSTÍN" },
    { id: "630", label: "SANTA MARÍA" },
    { id: "631", label: "SUAZA" },
    { id: "632", label: "TARQUI" },
    { id: "633", label: "TESALIA" },
    { id: "634", label: "TELLO" },
    { id: "635", label: "TERUEL" },
    { id: "636", label: "TIMANÁ" },
    { id: "637", label: "VILLAVIEJA" },
    { id: "638", label: "YAGUARÁ" },
  ],
  "14": [
    { id: "639", label: "RIOHACHA" },
    { id: "640", label: "ALBANIA" },
    { id: "641", label: "BARRANCAS" },
    { id: "642", label: "DIBULLA" },
    { id: "643", label: "DISTRACCIÓN" },
    { id: "644", label: "EL MOLINO" },
    { id: "645", label: "FONSECA" },
    { id: "646", label: "HATONUEVO" },
    { id: "647", label: "LA JAGUA DEL PILAR" },
    { id: "648", label: "MAICAO" },
    { id: "649", label: "MANAURE" },
    { id: "650", label: "SAN JUAN DEL CESAR" },
    { id: "651", label: "URIBIA" },
    { id: "652", label: "URUMITA" },
    { id: "653", label: "VILLANUEVA" },
  ],
  "15": [
    { id: "654", label: "SANTA MARTA" },
    { id: "655", label: "ALGARROBO" },
    { id: "656", label: "ARACATACA" },
    { id: "657", label: "ARIGUANÍ EL DÍFICIL" },
    { id: "658", label: "CERRO SAN ANTONIO" },
    { id: "659", label: "CHIBOLO" },
    { id: "660", label: "CIÉNAGA" },
    { id: "661", label: "CONCORDIA" },
    { id: "662", label: "EL BANCO" },
    { id: "663", label: "EL PIÑON" },
    { id: "664", label: "EL RETÉN" },
    { id: "665", label: "FUNDACIÓN" },
    { id: "666", label: "GUAMAL" },
    { id: "667", label: "NUEVA GRANADA" },
    { id: "668", label: "PEDRAZA" },
    { id: "669", label: "PIJIÑO DEL CARMEN" },
    { id: "670", label: "PIVIJAY" },
    { id: "671", label: "PLATO" },
    { id: "672", label: "PUEBLOVIEJO" },
    { id: "673", label: "REMOLINO" },
    { id: "674", label: "SABANAS DE SAN ANGEL" },
    { id: "675", label: "SALAMINA" },
    { id: "676", label: "SAN SEBASTIÁN DE BUENAVIS" },
    { id: "677", label: "SAN ZENÓN" },
    { id: "678", label: "SANTA ANA" },
    { id: "679", label: "SANTA BÁRBARA PINTO" },
    { id: "680", label: "SITIONUEVO" },
    { id: "681", label: "TENERIFE" },
    { id: "682", label: "ZAPAYÁN" },
    { id: "683", label: "ZONA BANANERA" },
  ],
  "16": [
    { id: "684", label: "VILLAVICENCIO" },
    { id: "685", label: "ACACÍAS" },
    { id: "686", label: "BARRANCA DE UPÍA" },
    { id: "687", label: "CABUYARO" },
    { id: "688", label: "CASTILLA LA NUEVA" },
    { id: "689", label: "CUBARRAL" },
    { id: "690", label: "CUMARAL" },
    { id: "691", label: "EL CALVARIO" },
    { id: "692", label: "EL CASTILLO" },
    { id: "693", label: "EL DORADO" },
    { id: "694", label: "FUENTE DE ORO" },
    { id: "695", label: "GRANADA" },
    { id: "696", label: "GUAMAL" },
    { id: "697", label: "MAPIRIPÁN" },
    { id: "698", label: "MESETAS" },
    { id: "699", label: "LA MACARENA" },
    { id: "700", label: "LA URIBE" },
    { id: "701", label: "LEJANÍAS" },
    { id: "702", label: "PUERTO CONCORDIA" },
    { id: "703", label: "PUERTO GAITÁN" },
    { id: "704", label: "PUERTO LÓPEZ" },
    { id: "705", label: "PUERTO LLERAS" },
    { id: "706", label: "PUERTO RICO" },
    { id: "707", label: "RESTREPO" },
    { id: "708", label: "SAN CARLOS DE GUAROA" },
    { id: "709", label: "SAN JUAN DE ARAMA" },
    { id: "710", label: "SAN JUANITO" },
    { id: "711", label: "SAN MARTÍN" },
    { id: "712", label: "VISTAHERMOSA" },
  ],
  "17": [
    { id: "713", label: "PASTO" },
    { id: "714", label: "ALBÁN SAN JOSÉ" },
    { id: "715", label: "ALDANA" },
    { id: "716", label: "ANCUYÁ" },
    { id: "717", label: "ARBOLEDA BERRUECOS" },
    { id: "718", label: "BARBACOAS" },
    { id: "719", label: "BELÉN" },
    { id: "720", label: "BUESACO" },
    { id: "721", label: "COLÓN GENOVA" },
    { id: "722", label: "CONSACÁ" },
    { id: "723", label: "CONTADERO" },
    { id: "724", label: "CÓRDOBA" },
    { id: "725", label: "CUASPUD CARLOSAMA" },
    { id: "726", label: "CUMBAL" },
    { id: "727", label: "CUMBITARA" },
    { id: "728", label: "CHACHAGUÍ" },
    { id: "729", label: "EL CHARCO" },
    { id: "730", label: "EL PEÑOL" },
    { id: "731", label: "EL ROSARIO" },
    { id: "732", label: "EL TABLÓN DE GÓMEZ" },
    { id: "733", label: "EL TAMBO" },
    { id: "734", label: "FUNES" },
    { id: "735", label: "GUACHUCAL" },
    { id: "736", label: "GUAITARILLA" },
    { id: "737", label: "GUALMATÁN" },
    { id: "738", label: "ILES" },
    { id: "739", label: "IMUÉS" },
    { id: "740", label: "IPIALES" },
    { id: "741", label: "LA CRUZ" },
    { id: "742", label: "LA FLORIDA" },
    { id: "743", label: "LA LLANADA" },
    { id: "744", label: "LA TOLA" },
    { id: "745", label: "LA UNIÓN" },
    { id: "746", label: "LEIVA" },
    { id: "747", label: "LINARES" },
    { id: "748", label: "SOTOMAYOR" },
    { id: "749", label: "PAYAN" },
    { id: "750", label: "PIEDRANCHA" },
    { id: "751", label: "MOSQUERA" },
    { id: "752", label: "NARIÑO" },
    { id: "753", label: "OLAYA HERRERA" },
    { id: "754", label: "OSPINA" },
    { id: "755", label: "FRANCISCO PIZARRO" },
    { id: "756", label: "POLICARPA" },
    { id: "757", label: "POTOSÍ" },
    { id: "758", label: "PROVIDENCIA" },
    { id: "759", label: "PUERRES" },
    { id: "760", label: "PUPIALES" },
    { id: "761", label: "RICAURTE" },
    { id: "762", label: "ROBERTO PAYÁN (SAN JOSÉ )" },
    { id: "763", label: "SAMANIEGO" },
    { id: "764", label: "SANDONÁ" },
    { id: "765", label: "SAN BERNARDO" },
    { id: "766", label: "SAN LORENZO" },
    { id: "767", label: "SAN PABLO" },
    { id: "768", label: "SAN PEDRO DE CARTAGO" },
    { id: "769", label: "SANTA BÁRBARA (ISCUANDE)" },
    { id: "770", label: "GUACHAVES" },
    { id: "771", label: "SAPUYES" },
    { id: "772", label: "TAMINANGO" },
    { id: "773", label: "TANGUA" },
    { id: "774", label: "TUMACO" },
    { id: "775", label: "TÚQUERRES" },
    { id: "776", label: "YACUANQUER" },
  ],
  "18": [
    { id: "777", label: "CÚCUTA" },
    { id: "778", label: "ABREGO" },
    { id: "779", label: "ARBOLEDAS" },
    { id: "780", label: "BOCHALEMA" },
    { id: "781", label: "BUCARASICA" },
    { id: "782", label: "CÁCOTA" },
    { id: "783", label: "CACHIRA" },
    { id: "784", label: "CHINÁCOTA" },
    { id: "785", label: "CHITAGÁ" },
    { id: "786", label: "CONVENCIÓN" },
    { id: "787", label: "CUCUTA" },
    { id: "788", label: "DURANIA" },
    { id: "789", label: "EL CARMEN" },
    { id: "790", label: "EL TARRA" },
    { id: "791", label: "EL ZULIA" },
    { id: "792", label: "GRAMALOTE" },
    { id: "793", label: "HACARÍ" },
    { id: "794", label: "HERRÁN" },
    { id: "795", label: "LABATECA" },
    { id: "796", label: "LA ESPERANZA" },
    { id: "797", label: "LA PLAYA" },
    { id: "798", label: "LOS PATIOS" },
    { id: "799", label: "LOURDES" },
    { id: "800", label: "MUTISCUA" },
    { id: "801", label: "OCAÑA" },
    { id: "802", label: "PAMPLONA" },
    { id: "803", label: "PAMPLONITA" },
    { id: "804", label: "PUERTO SANTANDER" },
    { id: "805", label: "RAGONVALIA" },
    { id: "806", label: "SALAZAR" },
    { id: "807", label: "SAN CALIXTO" },
    { id: "808", label: "SAN CAYETANO" },
    { id: "809", label: "SANTIAGO" },
    { id: "810", label: "SARDINATA" },
    { id: "811", label: "SILOS" },
    { id: "812", label: "TEORAMA" },
    { id: "813", label: "TIBÚ" },
    { id: "814", label: "TOLEDO" },
    { id: "815", label: "VILLA CARO" },
    { id: "816", label: "VILLA ROSARIO" },
  ],
  "19": [
    { id: "817", label: "ARMENIA" },
    { id: "818", label: "BUENAVISTA" },
    { id: "819", label: "CALARCA" },
    { id: "820", label: "CIRCASIA" },
    { id: "821", label: "CÓRDOBA" },
    { id: "822", label: "FILANDIA" },
    { id: "823", label: "GÉNOVA" },
    { id: "824", label: "LA TEBAIDA" },
    { id: "825", label: "MONTENEGRO" },
    { id: "826", label: "PIJAO" },
    { id: "827", label: "QUIMBAYA" },
    { id: "828", label: "SALENTO" },
  ],
  "20": [
    { id: "829", label: "PEREIRA" },
    { id: "830", label: "APÍA" },
    { id: "831", label: "BALBOA" },
    { id: "832", label: "BELÉN DE UMBRÍA" },
    { id: "833", label: "DOSQUEBRADAS" },
    { id: "834", label: "GUÁTICA" },
    { id: "835", label: "LA CELIA" },
    { id: "836", label: "LA VIRGINIA" },
    { id: "837", label: "MARSELLA" },
    { id: "838", label: "MISTRATÓ" },
    { id: "839", label: "PUEBLO RICO" },
    { id: "840", label: "QUINCHÍA" },
    { id: "841", label: "SANTA ROSA DE CABAL" },
    { id: "842", label: "SANTUARIO" },
  ],
  "21": [
    { id: "843", label: "BUCARAMANGA" },
    { id: "844", label: "AGUADA" },
    { id: "845", label: "ALBANIA" },
    { id: "846", label: "ARATOCA" },
    { id: "847", label: "BARBOSA" },
    { id: "848", label: "BARICHARA" },
    { id: "849", label: "BARRANCABERMEJA" },
    { id: "850", label: "BETULIA" },
    { id: "851", label: "BOLÍVAR" },
    { id: "852", label: "CABRERA" },
    { id: "853", label: "CALIFORNIA" },
    { id: "854", label: "CAPITANEJO" },
    { id: "855", label: "CARCASÍ" },
    { id: "856", label: "CEPITÁ" },
    { id: "857", label: "CERRITO" },
    { id: "858", label: "CHARALÁ" },
    { id: "859", label: "CHARTA" },
    { id: "860", label: "CHIMA" },
    { id: "861", label: "CHIPATÁ" },
    { id: "862", label: "CIMITARRA" },
    { id: "863", label: "CONCEPCIÓN" },
    { id: "864", label: "CONFINES" },
    { id: "865", label: "CONTRATACIÓN" },
    { id: "866", label: "COROMORO" },
    { id: "867", label: "CURITÍ" },
    { id: "868", label: "EL CARMEN DE CHUCURÍ" },
    { id: "869", label: "EL GUACAMAYO" },
    { id: "870", label: "EL PEÑÓN" },
    { id: "871", label: "EL PLAYÓN" },
    { id: "872", label: "ENCINO" },
    { id: "873", label: "ENCISO" },
    { id: "874", label: "FLORIÁN" },
    { id: "875", label: "FLORIDABLANCA" },
    { id: "876", label: "GALÁN" },
    { id: "877", label: "GAMBITA" },
    { id: "878", label: "GIRÓN" },
    { id: "879", label: "GUACA" },
    { id: "880", label: "GUADALUPE" },
    { id: "881", label: "GUAPOTÁ" },
    { id: "882", label: "GUAVATÁ" },
    { id: "883", label: "GUEPSA" },
    { id: "884", label: "HATO" },
    { id: "885", label: "JESÚS MARÍA" },
    { id: "886", label: "JORDÁN" },
    { id: "887", label: "LA BELLEZA" },
    { id: "888", label: "LANDÁZURI" },
    { id: "889", label: "LA PAZ" },
    { id: "890", label: "LEBRÍJA" },
    { id: "891", label: "LOS SANTOS" },
    { id: "892", label: "MACARAVITA" },
    { id: "893", label: "MÁLAGA" },
    { id: "894", label: "MATANZA" },
    { id: "895", label: "MOGOTES" },
    { id: "896", label: "MOLAGAVITA" },
    { id: "897", label: "OCAMONTE" },
    { id: "898", label: "OIBA" },
    { id: "899", label: "ONZAGA" },
    { id: "900", label: "PALMAR" },
    { id: "901", label: "PALMAS DEL SOCORRO" },
    { id: "902", label: "PÁRAMO" },
    { id: "903", label: "PIEDECUESTA" },
    { id: "904", label: "PINCHOTE" },
    { id: "905", label: "PUENTE NACIONAL" },
    { id: "906", label: "PUERTO PARRA" },
    { id: "907", label: "PUERTO WILCHES" },
    { id: "908", label: "RIONEGRO" },
    { id: "909", label: "SABANA DE TORRES" },
    { id: "910", label: "SAN ANDRÉS" },
    { id: "911", label: "SAN BENITO" },
    { id: "912", label: "SAN GIL" },
    { id: "913", label: "SAN JOAQUÍN" },
    { id: "914", label: "SAN JOSÉ DE MIRANDA" },
    { id: "915", label: "SAN MIGUEL" },
    { id: "916", label: "SAN VICENTE DE CHUCURI" },
    { id: "917", label: "SANTA BÁRBARA" },
    { id: "918", label: "SANTA HELENA DEL OPÓN" },
    { id: "919", label: "SIMACOTA" },
    { id: "920", label: "SOCORRO" },
    { id: "921", label: "SUAITA" },
    { id: "922", label: "SUCRE" },
    { id: "923", label: "SURATÁ" },
    { id: "924", label: "TONA" },
    { id: "925", label: "VALLE DE SAN JOSÉ" },
    { id: "926", label: "VÉLEZ" },
    { id: "927", label: "VETAS" },
    { id: "928", label: "VILLANUEVA" },
    { id: "929", label: "ZAPATOCA" },
  ],
  "22": [
    { id: "930", label: "SINCELEJO" },
    { id: "931", label: "BUENAVISTA" },
    { id: "932", label: "CAIMITO" },
    { id: "933", label: "COLOSO RICAURTE" },
    { id: "934", label: "COROZAL" },
    { id: "935", label: "COVEÑAS" },
    { id: "936", label: "CHALÁN" },
    { id: "937", label: "EL ROBLE" },
    { id: "938", label: "GALERAS NUEVA GRANADA" },
    { id: "939", label: "GUARANDA" },
    { id: "940", label: "LA UNIÓN" },
    { id: "941", label: "LOS PALMITOS" },
    { id: "942", label: "MAJAGUAL" },
    { id: "943", label: "MORROA" },
    { id: "944", label: "OVEJAS" },
    { id: "945", label: "PALMITO" },
    { id: "946", label: "SAMPUÉS" },
    { id: "947", label: "SAN BENITO ABAD" },
    { id: "948", label: "SAN JUAN DE BETULIA" },
    { id: "949", label: "SAN MARCOS" },
    { id: "950", label: "SAN ONOFRE" },
    { id: "951", label: "SAN PEDRO" },
    { id: "952", label: "SINCÉ" },
    { id: "953", label: "SUCRE" },
    { id: "954", label: "SANTIAGO DE TOLÚ" },
    { id: "955", label: "TOLUVIEJO" },
  ],
  "23": [
    { id: "956", label: "IBAGUÉ" },
    { id: "957", label: "ALPUJARRA" },
    { id: "958", label: "ALVARADO" },
    { id: "959", label: "AMBALEMA" },
    { id: "960", label: "ANZOÁTEGUI" },
    { id: "961", label: "ARMERO GUAYABAL" },
    { id: "962", label: "ATACO" },
    { id: "963", label: "CAJAMARCA" },
    { id: "964", label: "CARMEN DE APICALÁ" },
    { id: "965", label: "CASABIANCA" },
    { id: "966", label: "CHAPARRAL" },
    { id: "967", label: "COELLO" },
    { id: "968", label: "COYAIMA" },
    { id: "969", label: "CUNDAY" },
    { id: "970", label: "DOLORES" },
    { id: "971", label: "ESPINAL" },
    { id: "972", label: "FALAN" },
    { id: "973", label: "FLANDES" },
    { id: "974", label: "FRESNO" },
    { id: "975", label: "GUAMO" },
    { id: "976", label: "HERVEO" },
    { id: "977", label: "HONDA" },
    { id: "978", label: "ICONONZO" },
    { id: "979", label: "LÉRIDA" },
    { id: "980", label: "LÍBANO" },
    { id: "981", label: "MARIQUITA" },
    { id: "982", label: "MELGAR" },
    { id: "983", label: "MURILLO" },
    { id: "984", label: "NATAGAIMA" },
    { id: "985", label: "ORTEGA" },
    { id: "986", label: "PALOCABILDO" },
    { id: "987", label: "PIEDRAS" },
    { id: "988", label: "PLANADAS" },
    { id: "989", label: "PRADO" },
    { id: "990", label: "PURIFICACIÓN" },
    { id: "991", label: "RIOBLANCO" },
    { id: "992", label: "RONCESVALLES" },
    { id: "993", label: "ROVIRA" },
    { id: "994", label: "SALDAÑA" },
    { id: "995", label: "SAN ANTONIO" },
    { id: "996", label: "SAN LUIS" },
    { id: "997", label: "SANTA ISABEL" },
    { id: "998", label: "SUÁREZ" },
    { id: "999", label: "VALLE DE SAN JUAN" },
    { id: "1000", label: "VENADILLO" },
    { id: "1001", label: "VILLAHERMOSA" },
    { id: "1002", label: "VILLARRICA" },
  ],
  "24": [
    { id: "1003", label: "CALI" },
    { id: "1004", label: "ALCALÁ" },
    { id: "1005", label: "ANDALUCÍA" },
    { id: "1006", label: "ANSERMANUEVO" },
    { id: "1007", label: "ARGELIA" },
    { id: "1008", label: "BOLÍVAR" },
    { id: "1009", label: "BUENAVENTURA" },
    { id: "1010", label: "GUADALAJARA DE BUGA" },
    { id: "1011", label: "BUGALAGRANDE" },
    { id: "1012", label: "CAICEDONIA" },
    { id: "1013", label: "CALIMA DARIÉN" },
    { id: "1014", label: "CANDELARIA" },
    { id: "1015", label: "CARTAGO" },
    { id: "1016", label: "DAGUA" },
    { id: "1017", label: "EL ÁGUILA" },
    { id: "1018", label: "EL CAIRO" },
    { id: "1019", label: "EL CERRITO" },
    { id: "1020", label: "EL DOVIO" },
    { id: "1021", label: "FLORIDA" },
    { id: "1022", label: "GINEBRA" },
    { id: "1023", label: "GUACARÍ" },
    { id: "1024", label: "JAMUNDÍ" },
    { id: "1025", label: "LA CUMBRE" },
    { id: "1026", label: "LA UNIÓN" },
    { id: "1027", label: "LA VICTORIA" },
    { id: "1028", label: "OBANDO" },
    { id: "1029", label: "PALMIRA" },
    { id: "1030", label: "PRADERA" },
    { id: "1031", label: "RESTREPO" },
    { id: "1032", label: "RIOFRIO" },
    { id: "1033", label: "ROLDANILLO" },
    { id: "1034", label: "SAN PEDRO" },
    { id: "1035", label: "SEVILLA" },
    { id: "1036", label: "TORO" },
    { id: "1037", label: "TRUJILLO" },
    { id: "1038", label: "TULÚA" },
    { id: "1039", label: "ULLOA" },
    { id: "1040", label: "VERSALLES" },
    { id: "1041", label: "VIJES" },
    { id: "1042", label: "YOTOCO" },
    { id: "1043", label: "YUMBO" },
    { id: "1044", label: "ZARZAL" },
  ],
  "25": [
    { id: "1045", label: "ARAUCA" },
    { id: "1046", label: "ARAUQUITA" },
    { id: "1047", label: "CRAVO NORTE" },
    { id: "1048", label: "FORTUL" },
    { id: "1049", label: "PUERTO RONDÓN" },
    { id: "1050", label: "SARAVENA" },
    { id: "1051", label: "TAME" },
  ],
  "26": [
    { id: "1052", label: "YOPAL" },
    { id: "1053", label: "AGUAZUL" },
    { id: "1054", label: "CHAMEZA" },
    { id: "1055", label: "HATO COROZAL" },
    { id: "1056", label: "LA SALINA" },
    { id: "1057", label: "MANÍ" },
    { id: "1058", label: "MONTERREY" },
    { id: "1059", label: "NUNCHÍA" },
    { id: "1060", label: "OROCUÉ" },
    { id: "1061", label: "PAZ DE ARIPORO" },
    { id: "1062", label: "PORE" },
    { id: "1063", label: "RECETOR" },
    { id: "1064", label: "SABANALARGA" },
    { id: "1065", label: "SÁCAMA" },
    { id: "1066", label: "SAN LUIS DE PALENQUE" },
    { id: "1067", label: "TÁMARA" },
    { id: "1068", label: "TAURAMENA" },
    { id: "1069", label: "TRINIDAD" },
    { id: "1070", label: "VILLA NUEVA" },
  ],
  "27": [
    { id: "1071", label: "MOCOA" },
    { id: "1072", label: "COLÓN" },
    { id: "1073", label: "ORITO" },
    { id: "1074", label: "PUERTO ASÍS" },
    { id: "1075", label: "PUERTO CAICEDO" },
    { id: "1076", label: "PUERTO GUZMÁN" },
    { id: "1077", label: "PUERTO LEGUIZÁMO" },
    { id: "1078", label: "SIBUNDOY" },
    { id: "1079", label: "SAN FRANCISCO" },
    { id: "1080", label: "SAN MIGUEL" },
    { id: "1081", label: "SANTIAGO" },
    { id: "1082", label: "VALLE DEL GUAMUEZ (LA HOR" },
    { id: "1083", label: "VILLAGARZÓN" },
  ],
  "28": [
    { id: "1084", label: "SAN ANDRÉS" },
    { id: "1085", label: "PROVIDENCIA" },
  ],
  "29": [
    { id: "1086", label: "LETICIA" },
    { id: "1087", label: "EL ENCANTO" },
    { id: "1088", label: "LA CHORRERA" },
    { id: "1089", label: "LA PEDRERA" },
    { id: "1090", label: "LA VICTORIA" },
    { id: "1091", label: "MIRITI PARANÁ" },
    { id: "1092", label: "PUERTO ALEGRÍA" },
    { id: "1093", label: "PUERTO ARICA" },
    { id: "1094", label: "PUERTO NARIÑO" },
    { id: "1095", label: "PUERTO SANTANDER" },
    { id: "1096", label: "TARAPACÁ" },
  ],
  "30": [
    { id: "1097", label: "INÍRIDA" },
    { id: "1098", label: "BARRANCO MINAS" },
    { id: "1099", label: "MAPIRIPANA" },
    { id: "1100", label: "SAN FELIPE" },
    { id: "1101", label: "PUERTO COLOMBIA" },
    { id: "1102", label: "LA GUADALUPE" },
    { id: "1103", label: "CACAHUAL" },
    { id: "1104", label: "PANA PANA (CAMPO ALEGRE)" },
    { id: "1105", label: "MORICHAL NUEVO" },
  ],
  "31": [
    { id: "1106", label: "SAN JOSÉ DEL GUAVIARE" },
    { id: "1107", label: "CALAMAR" },
    { id: "1108", label: "EL RETORNO" },
    { id: "1109", label: "MIRAFLORES" },
  ],
  "32": [
    { id: "1110", label: "MITÚ" },
    { id: "1111", label: "CARURU" },
    { id: "1112", label: "PACOA" },
    { id: "1113", label: "TARAIRA" },
    { id: "1114", label: "PAPUNAUA (MORICHAL)" },
    { id: "1115", label: "YAVARATÉ" },
  ],
  "33": [
    { id: "1116", label: "PUERTO CARREÑO" },
    { id: "1117", label: "PRIMAVERA" },
    { id: "1118", label: "SANTA ROSALIA" },
    { id: "1119", label: "CUMARIBO" },
  ],
};

export const ACTIVIDADES: FieldOption[] = [
  {
    id: "30492",
    label: "130 · Propagación de plantas (actividades de los viveros, excepto viveros forestales).",
  },
  { id: "30500", label: "161 · Actividades de apoyo a la agricultura." },
  { id: "30501", label: "162 · Actividades de apoyo a la ganadería." },
  { id: "30506", label: "220 · Extracción de madera." },
  { id: "30507", label: "230 · Recolección de productos forestales diferentes a la madera." },
  { id: "30508", label: "240 · Servicios de apoyo a la silvicultura." },
  { id: "30509", label: "311 · Pesca marítima." },
  { id: "30513", label: "510 · Extracción de hulla (carbón de piedra)." },
  { id: "30514", label: "520 · Extracción de carbón lignito." },
  { id: "30515", label: "610 · Extracción de petróleo crudo." },
  { id: "30516", label: "620 · Extracción de gas natural." },
  { id: "30517", label: "710 · Extracción de minerales de hierro." },
  { id: "30518", label: "721 · Extracción de minerales de uranio y de torio." },
  { id: "30519", label: "722 · Extracción de oro y otros metales preciosos." },
  { id: "30520", label: "723 · Extracción de minerales de níquel." },
  { id: "30521", label: "729 · Extracción de otros minerales metalíferos no ferrosos n.c.p." },
  { id: "30522", label: "811 · Extracción de piedra, arena, arcillas comunes, yeso y anhidrita." },
  {
    id: "30523",
    label: "812 · Extracción de arcillas de uso industrial, caliza, caolín y bentonitas.",
  },
  { id: "30524", label: "820 · Extracción de esmeraldas, piedras preciosas y semipreciosas." },
  {
    id: "30525",
    label: "891 · Extracción de minerales para la fabricación de abonos y productos químicos.",
  },
  { id: "30526", label: "892 · Extracción de halita (sal)." },
  { id: "30527", label: "899 · Extracción de otros minerales no metálicos n.c.p." },
  {
    id: "30528",
    label: "910 · Actividades de apoyo para la extracción de petróleo y de gas natural.",
  },
  {
    id: "30529",
    label: "990 · Actividades de apoyo para otras actividades de explotación de minas y canteras.",
  },
  { id: "30530", label: "1011 · Procesamiento y conservación de carne y productos cárnicos." },
  { id: "30531", label: "1012 · Procesamiento y conservación de pescados, crustáceos y moluscos." },
  {
    id: "30532",
    label: "1020 · Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos.",
  },
  { id: "55317", label: "1031 · Extracción de aceites de origen vegetal crudos" },
  { id: "55318", label: "1032 · Elaboración de aceites y grasas de origen vegetal refinados" },
  { id: "55319", label: "1033 · Elaboración de aceites y grasas de origen animal" },
  { id: "30534", label: "1040 · Elaboración de productos lácteos." },
  { id: "30535", label: "1051 · Elaboración de productos de molinería." },
  { id: "30536", label: "1052 · Elaboración de almidones y productos derivados del almidón." },
  { id: "30537", label: "1061 · Trilla de café." },
  { id: "30538", label: "1062 · Descafeinado, tostión y molienda del café." },
  { id: "30539", label: "1063 · Otros derivados del café." },
  { id: "30540", label: "1071 · Elaboración y refinación de azúcar." },
  { id: "30541", label: "1072 · Elaboración de panela." },
  { id: "30542", label: "1081 · Elaboración de productos de panadería." },
  { id: "30543", label: "1082 · Elaboración de cacao, chocolate y productos de confitería." },
  {
    id: "30544",
    label: "1083 · Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares.",
  },
  { id: "30545", label: "1084 · Elaboración de comidas y platos preparados." },
  { id: "30546", label: "1089 · Elaboración de otros productos alimenticios n.c.p." },
  { id: "30547", label: "1090 · Elaboración de alimentos preparados para animales." },
  { id: "30548", label: "1101 · Destilación, rectificación y mezcla de bebidas alcohólicas." },
  { id: "30549", label: "1102 · Elaboración de bebidas fermentadas no destiladas." },
  {
    id: "30550",
    label: "1103 · Producción de malta, elaboración de cervezas y otras bebidas malteadas.",
  },
  {
    id: "30551",
    label:
      "1104 · Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas.",
  },
  { id: "30552", label: "1200 · Elaboración de productos de tabaco." },
  { id: "30553", label: "1311 · Preparación e hilatura de fibras textiles." },
  { id: "30554", label: "1312 · Tejeduría de productos textiles." },
  { id: "30555", label: "1313 · Acabado de productos textiles." },
  { id: "30556", label: "1391 · Fabricación de tejidos de punto y ganchillo." },
  {
    id: "30557",
    label: "1392 · Confección de artículos con materiales textiles, excepto prendas de vestir.",
  },
  { id: "30558", label: "1393 · Fabricación de tapetes y alfombras para pisos." },
  { id: "30559", label: "1394 · Fabricación de cuerdas, cordeles, cables, bramantes y redes." },
  { id: "30560", label: "1399 · Fabricación de otros artículos textiles n.c.p." },
  { id: "30561", label: "1410 · Confección de prendas de vestir, excepto prendas de piel." },
  { id: "30562", label: "1420 · Fabricación de artículos de piel." },
  { id: "30563", label: "1430 · Fabricación de artículos de punto y ganchillo." },
  { id: "30564", label: "1511 · Curtido y recurtido de cueros; recurtido y teñido de pieles." },
  {
    id: "30565",
    label:
      "1512 · Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería.",
  },
  {
    id: "30566",
    label:
      "1513 · Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales.",
  },
  {
    id: "30567",
    label: "1521 · Fabricación de calzado de cuero y piel, con cualquier tipo de suela.",
  },
  {
    id: "30568",
    label: "1522 · Fabricación de otros tipos de calzado, excepto calzado de cuero y piel.",
  },
  { id: "30569", label: "1523 · Fabricación de partes del calzado." },
  { id: "30570", label: "1610 · Aserrado, acepillado e impregnación de la madera." },
  {
    id: "30571",
    label:
      "1620 · Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles.",
  },
  {
    id: "30572",
    label:
      "1630 · Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción.",
  },
  { id: "30573", label: "1640 · Fabricación de recipientes de madera." },
  {
    id: "30574",
    label:
      "1690 · Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería.",
  },
  { id: "30575", label: "1701 · Fabricación de pulpas (pastas) celulósicas; papel y cartón." },
  {
    id: "30576",
    label:
      "1702 · Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.",
  },
  { id: "30577", label: "1709 · Fabricación de otros artículos de papel y cartón." },
  { id: "30578", label: "1811 · Actividades de impresión." },
  { id: "30579", label: "1812 · Actividades de servicios relacionados con la impresión." },
  { id: "30580", label: "1820 · Producción de copias a partir de grabaciones originales." },
  { id: "30581", label: "1910 · Fabricación de productos de hornos de coque." },
  { id: "30582", label: "1921 · Fabricación de productos de la refinación del petróleo." },
  { id: "30583", label: "1922 · Actividad de mezcla de combustibles." },
  { id: "30584", label: "2011 · Fabricación de sustancias y productos químicos básicos." },
  { id: "30585", label: "2012 · Fabricación de abonos y compuestos inorgánicos nitrogenados." },
  { id: "30586", label: "2013 · Fabricación de plásticos en formas primarias." },
  { id: "30587", label: "2014 · Fabricación de caucho sintético en formas primarias." },
  {
    id: "30588",
    label: "2021 · Fabricación de plaguicidas y otros productos químicos de uso agropecuario.",
  },
  {
    id: "30589",
    label:
      "2022 · Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas.",
  },
  {
    id: "30590",
    label:
      "2023 · Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador.",
  },
  { id: "30591", label: "2029 · Fabricación de otros productos químicos n.c.p." },
  { id: "30592", label: "2030 · Fabricación de fibras sintéticas y artificiales." },
  {
    id: "30593",
    label:
      "2100 · Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico.",
  },
  { id: "30594", label: "2211 · Fabricación de llantas y neumáticos de caucho" },
  { id: "30595", label: "2212 · Reencauche de llantas usadas" },
  {
    id: "30596",
    label: "2219 · Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.",
  },
  { id: "30597", label: "2221 · Fabricación de formas básicas de plástico." },
  { id: "30598", label: "2229 · Fabricación de artículos de plástico n.c.p." },
  { id: "30599", label: "2310 · Fabricación de vidrio y productos de vidrio." },
  { id: "30600", label: "2391 · Fabricación de productos refractarios." },
  { id: "30601", label: "2392 · Fabricación de materiales de arcilla para la construcción." },
  { id: "30602", label: "2393 · Fabricación de otros productos de cerámica y porcelana." },
  { id: "30603", label: "2394 · Fabricación de cemento, cal y yeso." },
  { id: "30604", label: "2395 · Fabricación de artículos de hormigón, cemento y yeso." },
  { id: "30605", label: "2396 · Corte, tallado y acabado de la piedra." },
  { id: "30606", label: "2399 · Fabricación de otros productos minerales no metálicos n.c.p." },
  { id: "30607", label: "2410 · Industrias básicas de hierro y de acero." },
  { id: "30608", label: "2421 · Industrias básicas de metales preciosos." },
  { id: "30609", label: "2429 · Industrias básicas de otros metales no ferrosos." },
  { id: "30610", label: "2431 · Fundición de hierro y de acero." },
  { id: "30611", label: "2432 · Fundición de metales no ferrosos." },
  { id: "30612", label: "2511 · Fabricación de productos metálicos para uso estructural." },
  {
    id: "30613",
    label:
      "2512 · Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías.",
  },
  {
    id: "30614",
    label:
      "2513 · Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central.",
  },
  { id: "30615", label: "2520 · Fabricación de armas y municiones." },
  { id: "30616", label: "2591 · Forja, prensado, estampado y laminado de metal; pulvimetalurgia." },
  { id: "30617", label: "2592 · Tratamiento y revestimiento de metales; mecanizado." },
  {
    id: "30618",
    label:
      "2593 · Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería.",
  },
  { id: "30619", label: "2599 · Fabricación de otros productos elaborados de metal n.c.p." },
  { id: "30620", label: "2610 · Fabricación de componentes y tableros electrónicos." },
  { id: "30621", label: "2620 · Fabricación de computadoras y de equipo periférico." },
  { id: "30622", label: "2630 · Fabricación de equipos de comunicación." },
  { id: "30623", label: "2640 · Fabricación de aparatos electrónicos de consumo." },
  { id: "30624", label: "2651 · Fabricación de equipo de medición, prueba, navegación y control." },
  { id: "30625", label: "2652 · Fabricación de relojes." },
  {
    id: "30626",
    label:
      "2660 · Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico.",
  },
  { id: "30627", label: "2670 · Fabricación de instrumentos ópticos y equipo fotográfico." },
  {
    id: "30628",
    label: "2680 · Fabricación de medios magnéticos y ópticos para almacenamiento de datos.",
  },
  {
    id: "30629",
    label: "2711 · Fabricación de motores, generadores y transformadores eléctricos.",
  },
  {
    id: "30630",
    label: "2712 · Fabricación de aparatos de distribución y control de la energía eléctrica.",
  },
  { id: "30631", label: "2720 · Fabricación de pilas, baterías y acumuladores eléctricos." },
  { id: "30632", label: "2731 · Fabricación de hilos y cables eléctricos y de fibra óptica." },
  { id: "30633", label: "2732 · Fabricación de dispositivos de cableado." },
  { id: "30634", label: "2740 · Fabricación de equipos eléctricos de iluminación." },
  { id: "30635", label: "2750 · Fabricación de aparatos de uso doméstico." },
  { id: "30636", label: "2790 · Fabricación de otros tipos de equipo eléctrico n.c.p." },
  {
    id: "30637",
    label: "2811 · Fabricación de motores, turbinas, y partes para motores de combustión interna.",
  },
  { id: "30638", label: "2812 · Fabricación de equipos de potencia hidráulica y neumática." },
  { id: "30639", label: "2813 · Fabricación de otras bombas, compresores, grifos y válvulas." },
  {
    id: "30640",
    label:
      "2814 · Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión.",
  },
  { id: "30641", label: "2815 · Fabricación de hornos, hogares y quemadores industriales." },
  { id: "30642", label: "2816 · Fabricación de equipo de elevación y manipulación." },
  {
    id: "30643",
    label:
      "2817 · Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico).",
  },
  { id: "30644", label: "2818 · Fabricación de herramientas manuales con motor." },
  {
    id: "30645",
    label: "2819 · Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.",
  },
  { id: "30646", label: "2821 · Fabricación de maquinaria agropecuaria y forestal." },
  {
    id: "30647",
    label: "2822 · Fabricación de máquinas formadoras de metal y de máquinas herramienta.",
  },
  { id: "30648", label: "2823 · Fabricación de maquinaria para la metalurgia." },
  {
    id: "30649",
    label:
      "2824 · Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción.",
  },
  {
    id: "30650",
    label: "2825 · Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco.",
  },
  {
    id: "30651",
    label:
      "2826 · Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros.",
  },
  {
    id: "30652",
    label: "2829 · Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.",
  },
  { id: "30653", label: "2910 · Fabricación de vehículos automotores y sus motores." },
  {
    id: "30654",
    label:
      "2920 · Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques.",
  },
  {
    id: "30655",
    label:
      "2930 · Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.",
  },
  { id: "30661", label: "3091 · Fabricación de motocicletas." },
  {
    id: "30662",
    label: "3092 · Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad.",
  },
  { id: "30663", label: "3099 · Fabricación de otros tipos de equipo de transporte n.c.p." },
  { id: "30664", label: "3110 · Fabricación de muebles." },
  { id: "30665", label: "3120 · Fabricación de colchones y somieres." },
  { id: "30666", label: "3210 · Fabricación de joyas, bisutería y artículos conexos." },
  { id: "30667", label: "3220 · Fabricación de instrumentos musicales." },
  { id: "30668", label: "3230 · Fabricación de artículos y equipo para la práctica del deporte." },
  { id: "30669", label: "3240 · Fabricación de juegos, juguetes y rompecabezas." },
  {
    id: "30670",
    label:
      "3250 · Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario).",
  },
  { id: "30671", label: "3290 · Otras industrias manufactureras n.c.p." },
  {
    id: "30672",
    label: "3311 · Mantenimiento y reparación especializado de productos elaborados en metal.",
  },
  { id: "30673", label: "3312 · Mantenimiento y reparación especializado de maquinaria y equipo." },
  {
    id: "30674",
    label: "3313 · Mantenimiento y reparación especializado de equipo electrónico y óptico.",
  },
  { id: "30675", label: "3314 · Mantenimiento y reparación especializado de equipo eléctrico." },
  {
    id: "30676",
    label:
      "3315 · Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas.",
  },
  {
    id: "30677",
    label: "3319 · Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.",
  },
  { id: "30678", label: "3320 · Instalación especializada de maquinaria y equipo industrial." },
  { id: "30679", label: "3511 · Generación de energía eléctrica." },
  { id: "30680", label: "3512 · Transmisión de energía eléctrica." },
  { id: "30681", label: "3513 · Distribución de energía eléctrica." },
  { id: "30682", label: "3514 · Comercialización de energía eléctrica." },
  {
    id: "30683",
    label: "3520 · Producción de gas; distribución de combustibles gaseosos por tuberías.",
  },
  { id: "30684", label: "3530 · Suministro de vapor y aire acondicionado." },
  { id: "30685", label: "3600 · Captación, tratamiento y distribución de agua." },
  { id: "30686", label: "3700 · Evacuación y tratamiento de aguas residuales." },
  { id: "30687", label: "3811 · Recolección de desechos no peligrosos." },
  { id: "30688", label: "3812 · Recolección de desechos peligrosos." },
  { id: "30689", label: "3821 · Tratamiento y disposición de desechos no peligrosos." },
  { id: "30690", label: "3822 · Tratamiento y disposición de desechos peligrosos." },
  { id: "30691", label: "3830 · Recuperación de materiales." },
  {
    id: "30692",
    label: "3900 · Actividades de saneamiento ambiental y otros servicios de gestión de desechos.",
  },
  { id: "30693", label: "4111 · Construcción de edificios residenciales." },
  { id: "30694", label: "4112 · Construcción de edificios no residenciales." },
  { id: "30695", label: "4210 · Construcción de carreteras y vías de ferrocarril." },
  { id: "30696", label: "4220 · Construcción de proyectos de servicio público." },
  { id: "30697", label: "4290 · Construcción de otras obras de ingeniería civil." },
  { id: "30698", label: "4311 · Demolición." },
  { id: "30699", label: "4312 · Preparación del terreno." },
  { id: "30700", label: "4321 · Instalaciones eléctricas." },
  { id: "30701", label: "4322 · Instalaciones de fontanería, calefacción y aire acondicionado." },
  { id: "30702", label: "4329 · Otras instalaciones especializadas." },
  { id: "30703", label: "4330 · Terminación y acabado de edificios y obras de ingeniería civil." },
  {
    id: "30704",
    label:
      "4390 · Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil.",
  },
  { id: "30705", label: "4511 · Comercio de vehículos automotores nuevos." },
  { id: "30706", label: "4512 · Comercio de vehículos automotores usados." },
  { id: "30707", label: "4520 · Mantenimiento y reparación de vehículos automotores." },
  {
    id: "30708",
    label:
      "4530 · Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.",
  },
  { id: "30709", label: "4541 · Comercio de motocicletas y de sus partes, piezas y accesorios." },
  {
    id: "30710",
    label: "4542 · Mantenimiento y reparación de motocicletas y de sus partes y piezas.",
  },
  {
    id: "30711",
    label: "4610 · Comercio al por mayor a cambio de una retribución o por contrata.",
  },
  {
    id: "30712",
    label: "4620 · Comercio al por mayor de materias primas agropecuarias; animales vivos.",
  },
  { id: "30713", label: "4631 · Comercio al por mayor de productos alimenticios." },
  { id: "30714", label: "4632 · Comercio al por mayor de bebidas y tabaco." },
  {
    id: "30715",
    label:
      "4641 · Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico.",
  },
  { id: "30716", label: "4642 · Comercio al por mayor de prendas de vestir." },
  { id: "30717", label: "4643 · Comercio al por mayor de calzado." },
  { id: "30718", label: "4644 · Comercio al por mayor de aparatos y equipo de uso doméstico." },
  {
    id: "30719",
    label:
      "4645 · Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador.",
  },
  { id: "30720", label: "4649 · Comercio al por mayor de otros utensilios domésticos n.c.p." },
  {
    id: "30721",
    label:
      "4651 · Comercio al por mayor de computadores, equipo periférico y programas de informática.",
  },
  {
    id: "30722",
    label:
      "4652 · Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones.",
  },
  { id: "30723", label: "4653 · Comercio al por mayor de maquinaria y equipo agropecuarios." },
  {
    id: "30724",
    label: "4659 · Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.",
  },
  {
    id: "30725",
    label:
      "4661 · Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos.",
  },
  { id: "30726", label: "4662 · Comercio al por mayor de metales y productos metalíferos." },
  {
    id: "30727",
    label:
      "4663 · Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción.",
  },
  {
    id: "30728",
    label:
      "4664 · Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario.",
  },
  { id: "30729", label: "4665 · Comercio al por mayor de desperdicios, desechos y chatarra." },
  { id: "30730", label: "4669 · Comercio al por mayor de otros productos n.c.p." },
  { id: "30731", label: "4690 · Comercio al por mayor no especializado." },
  {
    id: "30732",
    label:
      "4711 · Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco.",
  },
  {
    id: "30733",
    label:
      "4719 · Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco.",
  },
  {
    id: "30734",
    label:
      "4721 · Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados.",
  },
  {
    id: "30735",
    label:
      "4722 · Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados.",
  },
  {
    id: "30736",
    label:
      "4723 · Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados.",
  },
  {
    id: "30737",
    label:
      "4724 · Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados.",
  },
  {
    id: "30738",
    label:
      "4729 · Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados.",
  },
  { id: "30739", label: "4731 · Comercio al por menor de combustible para automotores." },
  {
    id: "30740",
    label:
      "4732 · Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores.",
  },
  {
    id: "30741",
    label:
      "4741 · Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados.",
  },
  {
    id: "30742",
    label:
      "4742 · Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados.",
  },
  {
    id: "30743",
    label: "4751 · Comercio al por menor de productos textiles en establecimientos especializados.",
  },
  {
    id: "30744",
    label:
      "4752 · Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados.",
  },
  {
    id: "30745",
    label:
      "4753 · Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados.",
  },
  {
    id: "30746",
    label:
      "4754 · Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación.",
  },
  {
    id: "30747",
    label: "4755 · Comercio al por menor de artículos y utensilios de uso doméstico.",
  },
  {
    id: "30748",
    label:
      "4759 · Comercio al por menor de otros artículos domésticos en establecimientos especializados.",
  },
  {
    id: "30749",
    label:
      "4761 · Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados.",
  },
  {
    id: "30750",
    label:
      "4762 · Comercio al por menor de artículos deportivos, en establecimientos especializados.",
  },
  {
    id: "30751",
    label:
      "4769 · Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados.",
  },
  {
    id: "30752",
    label:
      "4771 · Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados.",
  },
  {
    id: "30753",
    label:
      "4772 · Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.",
  },
  {
    id: "30754",
    label:
      "4773 · Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados.",
  },
  {
    id: "30755",
    label:
      "4774 · Comercio al por menor de otros productos nuevos en establecimientos especializados.",
  },
  { id: "30756", label: "4775 · Comercio al por menor de artículos de segunda mano." },
  {
    id: "30757",
    label:
      "4781 · Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles.",
  },
  {
    id: "30758",
    label:
      "4782 · Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles.",
  },
  {
    id: "30759",
    label: "4789 · Comercio al por menor de otros productos en puestos de venta móviles.",
  },
  { id: "30760", label: "4791 · Comercio al por menor realizado a través de internet." },
  {
    id: "30761",
    label: "4792 · Comercio al por menor realizado a través de casas de venta o por correo.",
  },
  {
    id: "30762",
    label:
      "4799 · Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.",
  },
  { id: "30765", label: "4921 · Transporte de pasajeros." },
  { id: "30766", label: "4922 · Transporte mixto." },
  { id: "30767", label: "4923 · Transporte de carga por carretera." },
  { id: "30768", label: "4930 · Transporte por tuberías." },
  { id: "30777", label: "5210 · Almacenamiento y depósito." },
  {
    id: "30778",
    label:
      "5221 · Actividades de estaciones, vías y servicios complementarios para el transporte terrestre.",
  },
  {
    id: "30780",
    label:
      "5223 · Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo.",
  },
  { id: "30781", label: "5224 · Manipulación de carga." },
  { id: "30782", label: "5229 · Otras actividades complementarias al transporte." },
  { id: "30783", label: "5310 · Actividades postales nacionales." },
  { id: "30784", label: "5320 · Actividades de mensajería." },
  { id: "30785", label: "5511 · Alojamiento en hoteles." },
  { id: "30786", label: "5512 · Alojamiento en apartahoteles." },
  { id: "30787", label: "5513 · Alojamiento en centros vacacionales." },
  { id: "30788", label: "5514 · Alojamiento rural." },
  { id: "30789", label: "5519 · Otros tipos de alojamientos para visitantes." },
  {
    id: "30790",
    label: "5520 · Actividades de zonas de camping y parques para vehículos recreacionales.",
  },
  { id: "30791", label: "5530 · Servicio por horas" },
  { id: "30792", label: "5590 · Otros tipos de alojamiento n.c.p." },
  { id: "30793", label: "5611 · Expendio a la mesa de comidas preparadas." },
  { id: "30794", label: "5612 · Expendio por autoservicio de comidas preparadas." },
  { id: "30795", label: "5613 · Expendio de comidas preparadas en cafeterías." },
  { id: "30796", label: "5619 · Otros tipos de expendio de comidas preparadas n.c.p." },
  { id: "30797", label: "5621 · Catering para eventos." },
  { id: "30798", label: "5629 · Actividades de otros servicios de comidas." },
  {
    id: "30799",
    label: "5630 · Expendio de bebidas alcohólicas para el consumo dentro del establecimiento.",
  },
  { id: "30800", label: "5811 · Edición de libros." },
  { id: "30801", label: "5812 · Edición de directorios y listas de correo." },
  {
    id: "30802",
    label: "5813 · Edición de periódicos, revistas y otras publicaciones periódicas.",
  },
  { id: "30803", label: "5819 · Otros trabajos de edición." },
  { id: "30804", label: "5820 · Edición de programas de informática (software)." },
  {
    id: "30805",
    label:
      "5911 · Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.",
  },
  {
    id: "30806",
    label:
      "5912 · Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.",
  },
  {
    id: "30807",
    label:
      "5913 · Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.",
  },
  {
    id: "30808",
    label: "5914 · Actividades de exhibición de películas cinematográficas y videos.",
  },
  { id: "30809", label: "5920 · Actividades de grabación de sonido y edición de música." },
  {
    id: "30810",
    label:
      "6010 · Actividades de programación y transmisión en el servicio de radiodifusión sonora.",
  },
  { id: "30811", label: "6020 · Actividades de programación y transmisión de televisión." },
  { id: "30812", label: "6110 · Actividades de telecomunicaciones alámbricas." },
  { id: "30813", label: "6120 · Actividades de telecomunicaciones inalámbricas." },
  { id: "30814", label: "6130 · Actividades de telecomunicación satelital." },
  { id: "30815", label: "6190 · Otras actividades de telecomunicaciones." },
  {
    id: "30816",
    label:
      "6201 · Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas).",
  },
  {
    id: "30817",
    label:
      "6202 · Actividades de consultoría informática y actividades de administración de instalaciones informáticas.",
  },
  {
    id: "30818",
    label:
      "6209 · Otras actividades de tecnologías de información y actividades de servicios informáticos.",
  },
  {
    id: "30819",
    label: "6311 · Procesamiento de datos, alojamiento (hosting) y actividades relacionadas.",
  },
  { id: "30820", label: "6312 · Portales web." },
  { id: "30821", label: "6391 · Actividades de agencias de noticias." },
  { id: "30822", label: "6399 · Otras actividades de servicio de información n.c.p." },
  { id: "30823", label: "6411 · Banco Central." },
  { id: "30824", label: "6412 · Bancos comerciales." },
  { id: "30825", label: "6421 · Actividades de las corporaciones financieras." },
  { id: "30826", label: "6422 · Actividades de las compañías de financiamiento." },
  { id: "30827", label: "6423 · Banca de segundo piso." },
  { id: "30828", label: "6424 · Actividades de las cooperativas financieras." },
  { id: "30829", label: "6431 · Fideicomisos, fondos y entidades financieras similares." },
  { id: "30830", label: "6432 · Fondos de cesantías." },
  { id: "30831", label: "6491 · Leasing financiero (arrendamiento financiero)." },
  {
    id: "30832",
    label:
      "6492 · Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario.",
  },
  { id: "30833", label: "6493 · Actividades de compra de cartera o factoring." },
  { id: "30834", label: "6494 · Otras actividades de distribución de fondos." },
  { id: "30835", label: "6495 · Instituciones especiales oficiales." },
  { id: "55320", label: "6496 · Capitalización" },
  {
    id: "30836",
    label:
      "6499 · Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.",
  },
  { id: "30837", label: "6511 · Seguros generales." },
  { id: "30838", label: "6512 · Seguros de vida." },
  { id: "30839", label: "6513 · Reaseguros." },
  { id: "55321", label: "6515 · Seguros de salud" },
  { id: "30841", label: "6521 · Servicios de seguros sociales de salud." },
  { id: "30842", label: "6522 · Servicios de seguros sociales de riesgos profesionales." },
  { id: "55322", label: "6523 · Servicios de seguros sociales en riesgos de familia" },
  { id: "30844", label: "6532 · Régimen de ahorro individual (RAI)." },
  { id: "30845", label: "6611 · Administración de mercados financieros." },
  { id: "30846", label: "6612 · Corretaje de valores y de contratos de productos básicos." },
  { id: "30847", label: "6613 · Otras actividades relacionadas con el mercado de valores." },
  { id: "30848", label: "6614 · Actividades de las casas de cambio." },
  { id: "30849", label: "6615 · Actividades de los profesionales de compra y venta de divisas." },
  {
    id: "30850",
    label: "6619 · Otras actividades auxiliares de las actividades de servicios financieros n.c.p.",
  },
  { id: "30851", label: "6621 · Actividades de agentes y corredores de seguros" },
  {
    id: "30852",
    label: "6629 · Evaluación de riesgos y daños, y otras actividades de servicios auxiliares",
  },
  { id: "30853", label: "6630 · Actividades de administración de fondos." },
  {
    id: "30854",
    label: "6810 · Actividades inmobiliarias realizadas con bienes propios o arrendados.",
  },
  {
    id: "30855",
    label:
      "6820 · Actividades inmobiliarias realizadas a cambio de una retribución o por contrata.",
  },
  { id: "30856", label: "6910 · Actividades jurídicas." },
  {
    id: "30857",
    label:
      "6920 · Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria.",
  },
  { id: "30858", label: "7010 · Actividades de administración empresarial." },
  { id: "30859", label: "7020 · Actividades de consultaría de gestión." },
  { id: "55323", label: "7111 · Actividades de arquitectura" },
  {
    id: "55324",
    label: "7112 · Actividades de ingenieria y otras actividades conexas de consultoria tecnica",
  },
  { id: "30861", label: "7120 · Ensayos y análisis técnicos." },
  {
    id: "30862",
    label:
      "7210 · Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería.",
  },
  {
    id: "30863",
    label:
      "7220 · Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades.",
  },
  { id: "30864", label: "7310 · Publicidad." },
  {
    id: "30865",
    label: "7320 · Estudios de mercado y realización de encuestas de opinión pública.",
  },
  { id: "30866", label: "7410 · Actividades especializadas de diseño." },
  { id: "30867", label: "7420 · Actividades de fotografía." },
  { id: "30868", label: "7490 · Otras actividades profesionales, científicas y técnicas n.c.p." },
  { id: "30869", label: "7500 · Actividades veterinarias." },
  { id: "30870", label: "7710 · Alquiler y arrendamiento de vehículos automotores." },
  { id: "30871", label: "7721 · Alquiler y arrendamiento de equipo recreativo y deportivo." },
  { id: "30872", label: "7722 · Alquiler de videos y discos." },
  {
    id: "30873",
    label:
      "7729 · Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.",
  },
  {
    id: "30874",
    label:
      "7730 · Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.",
  },
  {
    id: "30875",
    label:
      "7740 · Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor.",
  },
  { id: "30876", label: "7810 · Actividades de agencias de empleo." },
  { id: "30877", label: "7820 · Actividades de agencias de empleo temporal." },
  { id: "30878", label: "7830 · Otras actividades de suministro de recurso humano." },
  { id: "30879", label: "7911 · Actividades de las agencias de viaje." },
  { id: "30880", label: "7912 · Actividades de operadores turísticos." },
  { id: "30881", label: "7990 · Otros servicios de reserva y actividades relacionadas." },
  { id: "30882", label: "8010 · Actividades de seguridad privada." },
  { id: "30883", label: "8020 · Actividades de servicios de sistemas de seguridad." },
  { id: "30884", label: "8030 · Actividades de detectives e investigadores privados." },
  { id: "30885", label: "8110 · Actividades combinadas de apoyo a instalaciones." },
  { id: "30886", label: "8121 · Limpieza general interior de edificios." },
  {
    id: "30887",
    label: "8129 · Otras actividades de limpieza de edificios e instalaciones industriales.",
  },
  { id: "30888", label: "8130 · Actividades de paisajismo y servicios de mantenimiento conexos." },
  { id: "30889", label: "8211 · Actividades combinadas de servicios administrativos de oficina." },
  {
    id: "30890",
    label:
      "8219 · Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina.",
  },
  { id: "30891", label: "8220 · Actividades de centros de llamadas (Call center)." },
  { id: "30892", label: "8230 · Organización de convenciones y eventos comerciales." },
  {
    id: "30893",
    label: "8291 · Actividades de agencias de cobranza y oficinas de calificación crediticia.",
  },
  { id: "30894", label: "8292 · Actividades de envase y empaque." },
  { id: "30895", label: "8299 · Otras actividades de servicio de apoyo a las empresas n.c.p." },
  { id: "30906", label: "8511 · Educación de la primera infancia." },
  { id: "30907", label: "8512 · Educación preescolar." },
  { id: "30908", label: "8513 · Educación básica primaria." },
  { id: "30909", label: "8521 · Educación básica secundaria." },
  { id: "30910", label: "8522 · Educación media académica." },
  { id: "30911", label: "8523 · Educación media técnica y de formación laboral." },
  { id: "30912", label: "8530 · Establecimientos que combinan diferentes niveles de educación." },
  { id: "30913", label: "8541 · Educación técnica profesional." },
  { id: "30914", label: "8542 · Educación tecnológica." },
  {
    id: "30915",
    label: "8543 · Educación de instituciones universitarias o de escuelas tecnológicas.",
  },
  { id: "30916", label: "8544 · Educación de universidades." },
  { id: "30917", label: "8551 · Formación académica no formal." },
  { id: "30918", label: "8552 · Enseñanza deportiva y recreativa." },
  { id: "30919", label: "8553 · Enseñanza cultural." },
  { id: "30920", label: "8559 · Otros tipos de educación n.c.p." },
  { id: "30921", label: "8560 · Actividades de apoyo a la educación." },
  { id: "30922", label: "8610 · Actividades de hospitales y clínicas, con internación." },
  { id: "30923", label: "8621 · Actividades de la práctica médica, sin internación." },
  { id: "30924", label: "8622 · Actividades de la práctica odontológica." },
  { id: "30925", label: "8691 · Actividades de apoyo diagnóstico." },
  { id: "30926", label: "8692 · Actividades de apoyo terapéutico." },
  { id: "30927", label: "8699 · Otras actividades de atención de la salud humana." },
  {
    id: "30928",
    label: "8710 · Actividades de atención residencial medicalizada de tipo general.",
  },
  {
    id: "30929",
    label:
      "8720 · Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas.",
  },
  {
    id: "30930",
    label:
      "8730 · Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas.",
  },
  { id: "30931", label: "8790 · Otras actividades de atención en instituciones con alojamiento" },
  {
    id: "30932",
    label:
      "8810 · Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas.",
  },
  { id: "55325", label: "8891 · Actividades de guarderías para niños y niñas" },
  { id: "55326", label: "8899 · Otras actividades de asistencia social n.c.p." },
  { id: "30945", label: "9200 · Actividades de juegos de azar y apuestas." },
  { id: "30946", label: "9311 · Gestión de instalaciones deportivas." },
  { id: "30947", label: "9312 · Actividades de clubes deportivos." },
  { id: "30948", label: "9319 · Otras actividades deportivas." },
  { id: "30949", label: "9321 · Actividades de parques de atracciones y parques temáticos." },
  { id: "30950", label: "9329 · Otras actividades recreativas y de esparcimiento n.c.p." },
  { id: "30951", label: "9411 · Actividades de asociaciones empresariales y de empleadores" },
  {
    id: "30957",
    label: "9511 · Mantenimiento y reparación de computadores y de equipo periférico.",
  },
  { id: "30958", label: "9512 · Mantenimiento y reparación de equipos de comunicación." },
  { id: "30959", label: "9521 · Mantenimiento y reparación de aparatos electrónicos de consumo." },
  {
    id: "30960",
    label: "9522 · Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería.",
  },
  { id: "30961", label: "9523 · Reparación de calzado y artículos de cuero." },
  { id: "30962", label: "9524 · Reparación de muebles y accesorios para el hogar." },
  {
    id: "30963",
    label: "9529 · Mantenimiento y reparación de otros efectos personales y enseres domésticos.",
  },
  {
    id: "30964",
    label:
      "9601 · Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel.",
  },
  { id: "30965", label: "9602 · Peluquería y otros tratamientos de belleza." },
  { id: "30966", label: "9603 · Pompas fúnebres y actividades relacionadas." },
  { id: "30967", label: "9609 · Otras actividades de servicios personales n.c.p." },
];
